server:
  port: 777
gateway-server:
  serverName: test-provider
  center-addr: 127.0.0.1:18080
  safeKey: safeKey
  safeSecret: safeSecret
spring:
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
api:
  gateway:
    sdk:
      base-url: http://192.168.154.128         # 网关服务地址
      safe-key: safeKey                 # 从网关中心获取
      safe-secret: safeSecret           # 从网关中心获取
      connect-timeout: 5000             # 连接超时时间(ms)
      socket-timeout: 10000             # 读取超时时间(ms)
      max-connections: 100              # 最大连接数